#!/bin/bash
if [ -e $1 ];
then
  rm $1
fi
if [ "$2" = "gfortran" ];
then
  cc_file="$1.f"
else
  cc_file="$1.cc"
fi
no_file=$(find $cc_file)
if [ "$2" = "debug" ];
then
  debug="true"
  cpp="g++ -g -I /usr/local/include -L /usr/local/lib"
else
  debug="false"
  cpp="g++ -I /usr/local/include -L /usr/local/lib"
fi
if [ "$no_file" = "" ];
then
  echo ***Error: $cc_file does not exist***
else
  echo File $cc_file found, creating exe file
  if [ "$2" = "" ];
  then
     $cpp $cc_file -o $1
  else
     if [ $debug = "true" ];
     then
       if [ $3 = "" ];
       then
         $cpp $cc_file -o $1
       else
         $cpp $cc_file -o $1 -l$3
       fi
     else
       $cpp $cc_file -o $1 -l$2
     fi
  fi
  if [ -e $1 ];
  then
    echo Executable $1 was created!
    date
  fi
fi
