#!/bin/bash

# Remove the old exe if it exists
if [ -e $1 ];
then
  rm $1
fi

# Determine if the compiler is Fortran or C++
if [ "$2" = "gfortran" ];
then
  cc_file="$1.f"
else
  cc_file="$1.cc"
fi
# Remove the name of the exectuable from the list and save it for later
exe_name="$1"
shift
 
# Search for the file in the current directory
no_file=$(find $cc_file)
if [ "$no_file" = "" ];
then
  echo ***Error: $cc_file does not exist***
else
  if [ "$1" = "debug" ];
  then
    shift
    cpp="g++ -g -I /usr/local/include -I $PROJECTS_DIR/ -L /usr/local/lib -L $(pwd)"
  else
    cpp="g++ -I/usr/local/include -I $PROJECTS_DIR/ -L /usr/local/lib -L $(pwd)"
  fi
  echo File $cc_file found, creating exe file
  for lib in "$@"
  do
    libs="$libs -l$lib"
  done  
  $cpp -o $exe_name $cc_file $libs
  
  # Check if the exectuable was successfully made
  if [ -e $exe_name ];
  then
    echo Executable $exe_name was created!
    date
  fi
fi
